# Generated by Django 5.1.1 on 2024-09-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='image',
            field=models.ImageField(default='default_phone.png', upload_to='phones'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='release_data',
            field=models.DateField(),
        ),
    ]
