# Generated by Django 5.1.1 on 2024-09-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_alter_phone_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='release_data',
            field=models.DateField(null=True),
        ),
    ]
