# Generated by Django 5.1.1 on 2024-09-19 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_alter_phone_release_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='phone',
            unique_together={('name', 'price')},
        ),
    ]
