# Generated by Django 5.1.1 on 2024-09-19 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0005_alter_phone_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['name']},
        ),
    ]
